### ISSUE TITLE
Java Error on calling recognizeText

### ISSUE THREAD

**Issue by olivbd** [gustavomazzoni/cordova-plugin-tesseract#8]
Hi @gustavomazzoni 
I just followed your instructions to install this plugin and I tried it with a short sample code:

```
TesseractPlugin.loadLanguage('eng', function(c) {
  console.log("loadLanguage ok");
  TesseractPlugin.recognizeText(imageData, 'eng', function(recognizedText) {
    console.log(recognizedText);
  }, function(reason) {
    console.log('Error on recognizing text from image. ' + reason);
  });
});

```
After running it on an Android device, the only message which appears in the browser console is `loadLanguage ok`

Then, I typed `adb logcat`: 
```
V/TesseractPlugin(12960): Action: recognizeText
V/TesseractPlugin(12960): Starting process to recognize text in photo.
D/skia    (12960): --- SkImageDecoder::Factory returned null
V/TesseractPlugin(12960): Before baseApi
I/art     (12960): Rejecting re-init on previously-failed class java.lang.Class<com.googlecode.tesseract.android.TessBaseAPI>
W/System.err(12960): java.lang.UnsatisfiedLinkError: com.googlecode.tesseract.android.TessBaseAPI
W/System.err(12960): 	at com.gmazzoni.cordova.TesseractPlugin.recognizeText(TesseractPlugin.java:80)
W/System.err(12960): 	at com.gmazzoni.cordova.TesseractPlugin.execute(TesseractPlugin.java:48)
W/System.err(12960): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
W/System.err(12960): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
W/System.err(12960): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
W/System.err(12960): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err(12960): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(12960): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
W/System.err(12960): 	at android.os.Handler.dispatchMessage(Handler.java)
W/System.err(12960): 	at android.os.Looper.loop(Looper.java)
W/System.err(12960): 	at android.os.HandlerThread.run(HandlerThread.java)
```
What is missing?

**Comment by gustavomazzoni** [comment]
Hi @olivbd 

Weird! Look at this post: [java.lang.unsatisfiedlinkerror – How to handle Unsatisfied Link Error](https://examples.javacodegeeks.com/java-basics/exceptions/java-lang-unsatisfiedlinkerror-how-to-handle-unsatisfied-link-error/)

> The `UnsatisfiedLinkError` is thrown when an application attempts to load a native library like `.so` in Linux, `.dll` on Windows or `.dylib` in Mac and that library does not exist. Specifically, in order to find the required native library, the JVM looks in both the `PATH` environment variable and the `java.library.path` system property.

Looks like there is a problem with the `java.library.path` of your machine. Make sure you have the JRE / JDK working properly on your work environment.

PS: `TesseractPlugin.loadLanguage` function performs the download of the tessdata (language data) and so it is done assyncronously. When your callback function is called, it doesn't mean the download is done, it just means it has started. So that is why I recommended calling this function (`TesseractPlugin.loadLanguage`) as soon as your use case begins (any steps before calling `TesseractPlugin.recognizeText`).

**Comment by KYadav2016** [comment]
Hi @olivbd,
I was facing the same issue and installing NDK from [here](https://developer.android.com/ndk/guides/index.html) and then running this cmd "ndk-build" from [here](https://github.com/GautamGupta/Simple-Android-OCR/issues/6) solved the issue. 
complete solution is [here](https://github.com/rmtheis/tess-two/issues/42).

Hope this helps!

**Comment by cnjsweb** [comment]
I was having the `UnsatisfiedLinkError` recently as well. According to [this new comment](http://gaut.am/making-an-ocr-android-app-using-tesseract/#comment-196876) on an older 2014 tutorial, the default option is to use precompiled resources instead. I don't think you need to use NDK unless you _want_ to [build your own](https://github.com/rmtheis/tess-two/blob/master/BUILDING.md).

I updated my android platform's `build.gradle` file in [step 2.3 of the instructions](https://github.com/gustavomazzoni/cordova-plugin-tesseract#23-edit-your-projectplatformsandroidbuildgradle-file-and-add-tess-two-as-a-dependency-to-your-project-after--sub-project-dependencies-end-line) to incorporate the [pre-compiled resources](https://github.com/rmtheis/tess-two#usage).

Instead of:
```
compile project(':tess-two')
```
I used:
```
compile 'com.rmtheis:tess-two:6.1.1'
```

I'm not up and running yet, but this helped me get through the missing library issues above. The gradle files may need to be cleaned up a bit more. I'm working with Ionic 2, and the build process pulled in everything it needed so far. Good luck!
